DamnWidget/anaconda

README.md
This PR cleans and formats the README.md into a more consistent and better format which is more readable.
Changes open to discussion. :smile:
=> Cleanup and Re-Format README.md

commands/test_runner.py
=> Fixed: syntax not applied to test runner output

commands/test_runner.py
=> Feature #279: jump to source from test runner output

anaconda_lib/helpers.py, anaconda_lib/persistent_list.py, anaconda_lib/tooltips.py, anaconda_lib/worker.py
This pull request repairs #314 for us poor ol Windows users :smile: 
Cheers
Fotis
=> Corrected path names to work correctly on Windows systems

commands/test_runner.py
When the cursor is in a test case class definition line, command "run test under the cursor" runs all tests in this test case.
Tested with nosetests.
=> improve command "run test under the cursor"

Anaconda.sublime-settings
2 mini typos on the default settings.
=> 2 mini typos

anaconda_lib/linting/pep8.py
Hello, this PR simply upgrades pep8.py to 1.6.2.
1.6.2 fixes an issue with W503 and a few other improvements.
=> pep8 updated to 1.6.2

Anaconda.sublime-settings, anaconda_lib/linting/pep257.py
Add D309 to autoformat_ignore and pep8_ignore. Add D203 to pep257 ignore.
See issue https://github.com/DamnWidget/anaconda/issues/406 @DamnWidget 
I also noticed that 5 tests are failing on master before and after I had made changes, is this known?
=> #406 - update pep257 to 0.7.0. 

index.html
Updated the download link from 1.3.4 to 1.4.4
=> Fix downloadlink

Anaconda.sublime-settings, anaconda_lib/linting/sublime.py
Added solid, stipped and squiggly underlines
=> More mark styles

Anaconda.sublime-settings, commands/test_runner.py
This should make testing with Anaconda more flexible and usable on other testing frameworks.
=> Test improvements

Context.sublime-menu
Menu localization in Sublime Text requires menu entry id.
=> Add `id` to menu entries in Context.sublime-menu

anaconda_lib/linting/anaconda_mypy.py
=> Remove -dev from mypy version

anaconda_lib/linting/pycodestyle.py
The bundled version of pycodestyle is outdated and incorrectly marks some type annotations as errors. This is the latest version from GitHub master
=> Upgrade pycodestyle from 2.2.0 to 2.3.1

anaconda_server/jsonserver.py
Uses blocking kernel32.WaitForSingleObject to wait for ST3 process
without sleep/wake cycle, instead of "tasklist" external command call.
On Unix (Posix) it is still using sleep/wake cycle and os.kill(pid, 0)
to determine process state, since os.waitpid is possible only on
children.
=> Less CPU intrusive Windows process checker

Anaconda.sublime-settings
Heya, thank you for the great plugin. Just fixed a little typo that I encountered.
=> fixed typo

.travis.yml, anaconda_lib/linting/pyflakes/checker.py, anaconda_lib/linting/pyflakes/messages.py, messages/2.1.30.txt
Without this upgrade it's currently impossible to use pydantic models with Anaconda, and by extension the the awesome https://github.com/tiangolo/fastapi.
=> Upgrade pyflakes to 2.1.1, fixes #746

anaconda_server/jsonserver.py
=> fixes #820

anaconda_lib/workers/interpreter.py
Continuing from #769. I've had problems with multiple interpreters per project. When having multiple `.anaconda` files for different python interpreters within the same project, switching between them breaks because they all share the same project name. By allowing the user to configure the interpreter using something like `file:///path/to/my/venvs/venv/bin/python?project_name=my-project-name` in each `.anaconda` file, we can have multiple interpreter workers per project.
=> Allow params in file:// interpreter path

anaconda_server/jsonserver.py
=> Fix simple typo: incomming -> incoming

anaconda_lib/linting/anaconda_mypy.py
Tested with latest versions of anaconda/mypy
#847
=> Fixed mypy linting fatal error with current mypy v0.761 (Issue #847)

anaconda_lib/linting/anaconda_mypy.py, test/test_lint.py
- Fixes issue when displaying a url in mypy.
- Cleans up look of errors by trimming whitespace.
=> mypy colon fix
