- anaconda_lib/worker.py
Currently only absolute path for rcfile is supported. With these changes it's possible to specify project related rcfile.
```
{
"pylint_rcfile": "pylintrc"
}
```
> fixup: run server in project directory. Allows relative rcfile path #73

- anaconda_lib/linting/sublime.py
The linting icon path contains double slash 
eg:
Packages/Anaconda/anaconda_lib/linting//gutter_mark_themes/'
replaced it with:
Packages/Anaconda/anaconda_lib/linting/gutter_mark_themes/'
> Linting icon path fixed

- commands/test_runner.py
> test_path uses cross-platform path separator

- Default (Linux).sublime-keymap
- Default (OSX).sublime-keymap
- Default (Windows).sublime-keymap
Removed the keymap problem explained in https://github.com/DamnWidget/anaconda/issues/373. 
If a user wants this behavior, he can just add the keybinding himself but I'm pretty sure keeping this will confuse a bunch of vintage users (me included) in why suddenly some keys work differently. Especially with a lot of packages installed finding the source of this problem was quite tricky
> removed vintage keybinding, fixes #373

- anaconda_server/commands/doc.py
Using the vagrant_server branch, running `python server.py`, will constantly throw the following error:
error: uncaptured python exception, closing channel <__main__.JSONHandler connected 192.168.59.3:60400 at 0x7f40f1212dd8> (<class 'TypeError'>:__init__() missing 1 required positional argument: 'html' [/usr/local/lib/python3.4/asyncore.py|read|83] [/usr/local/lib/python3.4/asyncore.py|handle_read_event|442] [/usr/local/lib/python3.4/asynchat.py|handle_read|171] [../anaconda_server/jsonserver.py|found_terminator|93] [../anaconda_server/jsonserver.py|handle_command|111] [/anaconda/anaconda_server/handlers/jedi_handler.py|run|30] [/anaconda/anaconda_server/lib/anaconda_handler.py|run|48] [/anaconda/anaconda_server/handlers/jedi_handler.py|doc|98])
This occurs when the sublime user changes …
> html constructor arg default to None

- listeners/signatures.py
First of all, I'm new to this so I don't know whether I need to wait for someone to approve to create a pull request on the issue I reported. So apologies for not following protocol that I might be unaware of.
This would make it look like so:
Instead of so:
Notice that the second line of signature was completely absent from the popup, making this not just a formatting issue.
> Fix for #412

- templates/python_build.tpl
> Escape Python Interpretter by default in build system

- anaconda_lib/helpers.py
Anaconda crashes when opening a file located on a remote server accessed through [afuse](https://github.com/pcarrier/afuse) (a SSHFS helper).
This is caused the way afuse manages the directory where SSHFS mount points are stored. In this particular directory, ``if os.path.exists(environfile)`` will always return ``True``, resulting in a ``.anaconda`` file trying to be opened. This operation will fail with an ``OSError`` exception being thrown as shown in the following traceback:
```
Traceback (most recent call last):
File "/usr/local/sublime-text-3/sublime_plugin.py", line 304, in on_activated
callback.on_activated(v)
File "/home/oyaji/.config/sublime-text-3/Packages/Anaconda/listeners/linting.py", line 118, in on_activated
self.run_linter(view)
File …
```
> Fix compatibility issue with afuse

- commands/autoimport.py
If there is no def or class definition, then try to look for an import statement and place the new autoimort rigth after. #Fixes #434
> Fix for #434 - autoimport fails when no def or class definition

- Anaconda.sublime-settings
E261 should read "Fix spacing before comment hash", not after
> Fix typo in Anaconda default settings

- Anaconda.sublime-settings
- commands/test_runner.py
Hello, I ran into some issues with the test runner and py.test's requirements for specifying test paths, so I've whipped up a quick fix. I hope it's useful!
py.test requires the following format when specifying targeted tests:
> py.test path/to/file.py::ModuleName::test_name
Because of this, the `Run Current Test` and `Run Current File Tests` commands
produced test paths that were incompatible with py.test.
This commit adds:
- a `test_filepath_patterns` setting that tells the Test Runner
to use filepaths when building test pattern paths.
- an additional delimeter setting named `test_method_delimeter` that allows
the user to specify the delimeter to be used to separate the targeted class
and method.
Recommended settings for py.test users:
- test_delimeter: "::"
- test_method_delimeter: …
> Bugfix: Additional py.test support for Test Runner

- listeners/linting.py
When "anaconda_linter_persistent" is "false" and "anaconda_linting_behaviour" is not "always" anaconda wasn't erasing linter marks while you type.
Fixed without really understanding the code, perhaps some lines should be moved from `if check_linting_behaviour(view, ['always']):`
> Fixed Anaconda not erasing linter marks

- anaconda_server/commands/doc.py
- listeners/signatures.py
Hi,
I've been using Anaconda for a while (thanks!), so figured I'd try and help out with some fixing. This is my first pull request, so let me know if I've done anything wrong :)
---
I started reading the developer's book [here](https://www.gitbook.com/book/damnwidget/anacondast3-developers-documentation/details).
The section there 'The Development Workflow' mentions _Make sure that you add an entry about the new fix/feature that you introduced into anaconda in the relnotes index_ with a link to:
https://github.com/DamnWidget/anaconda/blob/master/templates/relnotes.tpl
which gives a 404, so I've not done whatever that was meant to cover.
I kept reading and came to another dead link when I got to unit testing:
https://damnwidget.gitbooks.io/using_github/README.html#anacondas-development-pro …
> Fix tooltips for function signatures and docstrings which contain special HTML characters. Fixes #417

- listeners/signatures.py
Hi,
Thanks for taking my last fix. Here's another small fix, this time for issue #416.
Specific changes:
* Typing Python's `None` displays the signature `NoneType` for me, so exclude that.
* Clean up the checking for excluded signatures and move it to a helper method. The checking didn't work for me, because for example the signature for `int` was of the format `int int(...`, so as well as splitting on `(` also split on whitespace to get the name.
Tested by checking that signatures are not shown for each of the `exclude`s by typing:
```py
str()
bool()
False and True
None and False
int
1234
1.2354
```
But are for a few other things like:
```py
tuple()
list()
input
```
> Fix excluding signatures for numbers and constants like 'True'. Fixes #416

- anaconda_server/commands/doc.py
Doc._html uses a direct check on the python version while the import tries to rely on importing html failing.  Related to #476, this is a problem if an html package is installed in Python 2 and doesn't trigger the exception.  Instead just using the same version check from Doc._html
> Update to doc.py to fix html/cgi import problem

- commands/next_lint_error.py
Trying to go to next error when current line is >= than last error line triggers an exception.
This fixes the bug and also makes Next error go to the first error if we’re already at the last error.
> Fixes #524

- Context.sublime-menu
- Default.sublime-commands
- commands/__init__.py
- commands/prev_lint_error.py
I find it especially useful in large files where all or most of the code is written by someone else. Moving back and forth between linting errors makes it easier to understand the style used in that file/project.
> Implement prev_lint_error command

- anaconda_lib/explore_panel.py
After jumping to definition within single file one can't return by `jump_back` command. 
`Default.history_list.JumpHistoryUpdater` pushes selection to jump history on `goto_definition` command so anaconda must do the same.
> Push selection to jump_history before jump

- anaconda_server/commands/goto.py
Allows to jump to "import" assignment if there are no definitions.
```
file1.py:
SOME_CONST = 0
```
```
file2.py:
from file1 import SOME_CONST
...
print(SOME_CONST)
```
Now one can jump to import assignment from line with `print` statement.
> Jump to assignment if there are no definitions

- Anaconda.sublime-settings
- commands/test_runner.py
Some testing libraries need params/switches to run a specific test.
For example, [Specter](http://specter.readthedocs.io/en/latest/using/index.html#runner):
- needs `--select-module` for the _Run current file tests_ command
- needs `--select-tests` for the _Run current test_ command
Also Python's unittest needs a `-s` switch to run a specific test.
Add `test_params` setting as a dict where you can specify params for all three testing commands.
> Add scope-specific test params

- Anaconda.sublime-settings
This change should only change the text in comments.
The purpose is to make the punctuation consistent and correct non-standard grammar and spelling in the comments.
> Clean up grammar and spelling in Anaconda.sublime-settings.

- commands/goto.py
Fixes: ImportError: No module named 'Anaconda.anaconda_lib.helper'.
> Fixes small typo that causes Anaconda not be loaded.

- anaconda_server/commands/autoformat.py
- commands/autoformat.py
Previously reformat hard-coded (defaulted to) 4 spaces for indent. This can be useful for everyone using other than 4 spaces indent like us.
> Respect indent setting when doing reformat

- Anaconda.sublime-settings
- anaconda_lib/linting/sublime.py
- anaconda_lib/phantoms.py
- css/phantom.css
- templates/phantoms/default.tpl
Sublime Text 3 Build 3124 introduced the [Phantoms](http://www.sublimetext.com/docs/3/api_reference.html#sublime.Phantom) API, allows HTML annotations to be added to the text buffer by plugins.
This PR allow show linting errors inline using this new API, also adding a new setting `anaconda_linter_phantoms` to turn on this feature (default off).
> allow show linting errors inline

- anaconda_lib/linting/sublime.py
Presently the phantoms join all messages on a single line. Additionally, if there are messages of different levels, all of the messages on each line are duplicated (once per error level). This makes reading phantoms difficult.
This change puts one error message per line, always with the proper level coloring.
> Update phantoms to add one message per line

- Anaconda.sublime-settings
Fixed what I assume is a typo in the default settings comments
> Fix two typos in default settings

- commands/goto.py
`data` may contain an `error` instead of a `result` and that line would fail with a `KeyError` instead of falling back to the builtin Goto.
> Check for result existence first

- Anaconda.sublime-settings
pep8 (previously broken): https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes
pep257: http://www.pydocstyle.org/en/2.1.1/error_codes.html
> Update error code links in settings

- anaconda_lib/linting/sublime.py
When setting `mypy_silent_imports` or `mypy_almost_silent`, linting with mypy will stop working altogether.
The following flags of mypy have been deprecated in version 0.6 and will result in warnings, which somehow prevent Anaconda Sublime from receiving linting outputs:
```
mypy --silent-imports
Warning: --silent-imports has been replaced by --ignore-missing-imports --follow-imports=skip
mypy --almost-silent
Warning: --almost-silent has been replaced by --follow-imports=errors
mypy --follow-imports=errors
mypy: error: argument --follow-imports: invalid choice: 'errors' (choose from 'normal', 'silent', 'skip', 'error')
```
> Fix mypy setting mypy_silent_imports and mypy_almost_silent

- Anaconda.sublime-settings
- anaconda_lib/helpers.py
Use case:
Working in a monorepo with multiple python projects. Each project has its own virtualenv. This allows me to have a single `.anaconda` file in each of the python projects, but only using a single sublime project.
This should not break the current behavior in any way, only expand to it.
> Allow multiple .anaconda files in a single project

- anaconda_lib/helpers.py
- anaconda_lib/workers/local_worker.py
Permits user to define a longer timeout (e.g 0.5) without swallowing all errors and having potential silent fails in future
> Add new setting 'socket_timeout' for slow jsonserver/jsonclient connect

- anaconda_server/jsonserver.py
Hey,
on the latest windows WSL (update 1903), the created socket file gets a 0o000 permission regardless of the current umask. I managed to reproduce it in Python and this seems to be the fix for it.
Also might be related to https://github.com/Microsoft/WSL/issues/352
> WSL 1903 fix for socketfile creation

- anaconda_lib/helpers.py
Fix the issue #517.
The problem is: If we try to run the `sublime.expand_variables` first, it will remove variables not found in `window.extract_variables()`. So when the code reaches the next line, the variable that exists in `os.environ` will not be replaced.
Example:
```
>>> path = '$VIRTUAL_ENV/bin/python'
>>> sublime.expand_variables(path, window.extract_variables())
'/bin/python'
```
With this fix, running `os.path.expanduser(os.path.expandvars(path))` first, will replace the `os.environ` variables, and it will **KEEP** variables that is not present. So when it reaches the next line, it will be able to replace any more window variables.
Example:
```
>>> window.extract_variables()
{'file_base_name': 'helpers'}
>>> os.environ
environ({'VIRTUAL_ENV': 'my_virtual_env_path'})
>>> path = …
```
> Change replace variables order

- commands/set_python_interpreter.py
Fixes raised AttributeError when sublime.active_window().project_data() returns None instead of an empty dict. Fixes case where there is no currently loaded project (e.g., just open a test.py file and want to change the anaconda interpreter without creating a new project).
> Fix AttributeError

- anaconda_lib/builder/python_builder.py
- anaconda_lib/workers/interpreter.py
python_build.tpl was being referenced in a relative path with raw `../../` rather than using the os.path.join invocation it was _already_ within. I'm guessing someone just didn't have their second coffee that day.
Also fixed is a schema parse problem in windows, where urlparse treats something like `c:\path\here` like a url with schema `c` and path `path\here`, which subsequently causes worker execution to fail with WinError 2 (frustratingly, the path reported in sublime console is the python_interpreter path as reported in sublime settings, not the actual path attempted by the subprocess command). I don't _love_ checking the schema length to check for this problem, but I don't know better check that isn't also needlessly complicated.
> Remove a cross-platform compat bug in python builder

- anaconda_lib/linting/anaconda_mypy.py
Currently mypy will follow imports in files and return all errors in these imported files.  This adds the `follow-imports silent` flag to mypy so that only results relevant to the current file are returned.
Should resolve https://github.com/DamnWidget/anaconda/issues/809
> Silence mypy followed imports

- anaconda_lib/workers/local_worker.py
https://github.com/DamnWidget/anaconda/issues/850#issuecomment-681808398
I too hit the invalid code example while quickly copying and pasting:
```python
In [1]: import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect("("localhost", 59199)")
File "<ipython-input-1-cb7c2f46ddd7>", line 1
import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect("("localhost", 59199)")
^
SyntaxError: invalid syntax
```
Fixed it since I had a couple minutes.
> Fix invalid syntax in help message output, mentioned in #850

- listeners/completion.py
Fixed bug when completion appears after ':' and ')' symbols in ST4
Fixes #891
> Completion bug fix in ST4
